# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Install dependencies
      run: go list -f '{{.Dir}}' -m | xargs -I {} go get -v {}

    - name: Build
      run: go list -f '{{.Dir}}' -m | xargs -I {} go build -v {}

    - name: Test
      run: go list -f '{{.Dir}}' -m | xargs -I {} go test -v {}
