version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "mounthly"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "mounthly"